### ISSUE TITLE
Don't work with Fragment with more than one child.

### ISSUE THREAD

**Issue by edimitchel** [kontrollanten/babel-plugin-preact-fragment#5]
Your plugin works well on compilation for preact, but, don't work as expected in runtime.

When fragment have more than one child, all the Fragment and his content is ignored (deleted).

**Comment by kontrollanten** [comment]
I've got it working with multiple children.

> Your plugin works well on compilation for preact, but, don't work as expected in runtime.

What's the difference between compilation for preact and runtime, in your case?

**Comment by edimitchel** [comment]
The compilation is the babel process.
The runtime is the execution on navigator. It's doesn't crash on runtime, but does not working as expected.

**Comment by kontrollanten** [comment]
Sorry for late answer. Yes, you're true. In my case (with @material-ui/icons pkg) there was only one child. I should've understood that multiple children wouldn't work. I've change the plugin so it won't do anything if there's more than one children, and also updated the readme. Thanks for your input!
